=== BlancaPenabad/LMSXI/Boletin4/4.21.dtd
<!ELEMENT pedido (datosCliente, productos)>
<!ELEMENT datosCliente (nombre, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombreP,precio)>
<!ELEMENT nombreP (#PCDATA)>
<!ELEMENT precio (#PCDATA)>


<!ATTLIST producto cantidad CDATA #REQUIRED>

=== BlancaPenabad/LMSXI/Boletin4/4.20.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido SYSTEM "4.21.dtd">
    <pedido>
        <datosCliente>
            <nombre>Blanca Penabad Villar</nombre>
            <direccion>Rúa Xeneral Pardiñas</direccion>
        </datosCliente>
        <productos>
                <producto cantidad="1">
                    <nombreP>Japi Mil</nombreP>
                    <precio>10</precio>
                </producto>
                <producto cantidad="2">
                    <nombreP>Alitas hot</nombreP>
                    <precio>6</precio>
                </producto>
                <producto cantidad="2">
                    <nombreP>Sprite</nombreP>
                    <precio>2</precio>
                </producto>
        </productos>
    </pedido>
